name: CI

on:
  pull_request:
        types: [opened, reopened, synchronize]
        branches: [main]

jobs:
  CI:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Pytest
        run: uv run pytest tests
